language: c

sudo: required
dist: trusty

# Xcode 7.3.1, OS X 10.11
# Xcode 8.3.3, OS X 10.12
#  - xcode7.3

#osx_image:
#  - xcode7.3

os:
  - linux
#  - osx

#compiler:
#  - clang
#  - gcc

services:
  - docker

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gettext check bullet dbus fontconfig freetype fribidi gst-plugins-good gstreamer luajit openssl webp libsndfile glib libspectre libraw librsvg poppler lz4; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ubuntu:16.04; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull ubuntu:17.04; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull fedora:25; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull fedora:26; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull opensuse:42.2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull opensuse:42.3; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull debian:8.9; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull debian:9.1; fi

#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull mageia:6; fi

#  - env: DISTRO=Opensuse422
#  - env: DISTRO=Opensuse423
#  - env: DISTRO=Mageia6
matrix:
  include:
  - env: DISTRO=Ubuntu1604
  - env: DISTRO=Ubuntu1704
  - env: DISTRO=Fedora25
  - env: DISTRO=Fedora26
  - env: DISTRO=Fedora26-wayland
  - env: DISTRO=Fedora26-misc
  - env: DISTRO=Debian89
  - env: DISTRO=Debian91

#  - os: osx
#    osx_image: xcode7.3
#  - os: osx
#    osx_image: xcode8.3

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$DISTRO" != "" ]]; then docker build -f  .ci/Dockerfile-$DISTRO . ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p ~/Library/LaunchAgents; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ln -sfv /usr/local/opt/d-bus/*.plist ~/Library/LaunchAgents; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then launchctl load ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="$(brew --prefix gettext)/bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export COPTS="--with-crypto=none --disable-pulseaudio --disable-cxx-bindings"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  ./autogen.sh $COPTS; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  make -j 10; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  make -j 10 examples; fi
#
# TRAVIS_EVENT_TYPE==cron as test for nightly builds
